# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: constant.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63onstant.proto\x12\x06totoro*O\n\tChunkType\x12\x16\n\x12\x43HUNK_TYPE_UNKNOWN\x10\x00\x12\x14\n\x10\x43HUNK_TYPE_NAIVE\x10\x01\x12\x14\n\x10\x43HUNK_TYPE_PAPER\x10\x02*\xb4\x01\n\x08\x46ileType\x12\x15\n\x11\x46ILE_TYPE_UNKNOWN\x10\x00\x12\x11\n\rFILE_TYPE_PDF\x10\x01\x12\x11\n\rFILE_TYPE_DOC\x10\x02\x12\x14\n\x10\x46ILE_TYPE_VISUAL\x10\x03\x12\x13\n\x0f\x46ILE_TYPE_AURAL\x10\x04\x12\x15\n\x11\x46ILE_TYPE_VIRTUAL\x10\x05\x12\x14\n\x10\x46ILE_TYPE_FOLDER\x10\x06\x12\x13\n\x0f\x46ILE_TYPE_OTHER\x10\x07*\x92\x01\n\x07LLMType\x12\x14\n\x10LLM_TYPE_UNKNOWN\x10\x00\x12\x11\n\rLLM_TYPE_CHAT\x10\x01\x12\x16\n\x12LLM_TYPE_EMBEDDING\x10\x02\x12\x18\n\x14LLM_TYPE_SPEECH2TEXT\x10\x03\x12\x17\n\x13LLM_TYPE_IMAGE2TEXT\x10\x04\x12\x13\n\x0fLLM_TYPE_RERANK\x10\x05*k\n\tLLMStatus\x12\x16\n\x12LLM_STATUS_UNKNOWN\x10\x00\x12\x15\n\x11LLM_STATUS_ACTIVE\x10\x01\x12\x17\n\x13LLM_STATUS_INACTIVE\x10\x02\x12\x16\n\x12LLM_STATUS_DELETED\x10\x03*&\n\nPromptType\x12\n\n\x06SIMPLE\x10\x00\x12\x0c\n\x08\x41\x44VANCED\x10\x01*1\n\x0f\x41ssistantStatus\x12\r\n\tAS_WASTED\x10\x00\x12\x0f\n\x0b\x41S_VALIDATE\x10\x01*I\n\x10\x43onversationRole\x12\x13\n\x0f\x43ONVE_ASSISTANT\x10\x00\x12\x0e\n\nCONVE_USER\x10\x01\x12\x10\n\x0c\x43ONVE_SYSTEM\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'constant_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHUNKTYPE']._serialized_start=26
  _globals['_CHUNKTYPE']._serialized_end=105
  _globals['_FILETYPE']._serialized_start=108
  _globals['_FILETYPE']._serialized_end=288
  _globals['_LLMTYPE']._serialized_start=291
  _globals['_LLMTYPE']._serialized_end=437
  _globals['_LLMSTATUS']._serialized_start=439
  _globals['_LLMSTATUS']._serialized_end=546
  _globals['_PROMPTTYPE']._serialized_start=548
  _globals['_PROMPTTYPE']._serialized_end=586
  _globals['_ASSISTANTSTATUS']._serialized_start=588
  _globals['_ASSISTANTSTATUS']._serialized_end=637
  _globals['_CONVERSATIONROLE']._serialized_start=639
  _globals['_CONVERSATIONROLE']._serialized_end=712
# @@protoc_insertion_point(module_scope)
