# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import constant_pb2 as constant__pb2
from . import doc_pb2 as doc__pb2
from . import pydantic_pb2 as pydantic__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservices.proto\x12\x06totoro\x1a\x0e\x63onstant.proto\x1a\tdoc.proto\x1a\x0epydantic.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xb4\x01\n\x10\x45mbeddingRequest\x12\x10\n\x08\x66ile_key\x18\x01 \x01(\t\x12\x0c\n\x04lang\x18\x02 \x01(\t\x12\x31\n\nchunk_type\x18\x03 \x01(\x0e\x32\x11.totoro.ChunkTypeR\nchunk_type\x12:\n\rparser_config\x18\x05 \x01(\x0b\x32\x14.totoro.ParserConfigR\rparser_config\x12\x11\n\tembedding\x18\x06 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMBEDDINGREQUEST']._serialized_start=129
  _globals['_EMBEDDINGREQUEST']._serialized_end=309
# @@protoc_insertion_point(module_scope)
